sudo: required
services:
  - docker

before_install:
  - docker build -t safiullahashfaq/docker-react -f Dockerfile.dev .

script:
  - docker run safiullahashfaq/docker-react npm run test -- --coverage
